// Code generated by wit-bindgen-go. DO NOT EDIT.

package conversion

import (
	"github.com/bytecodealliance/wasm-tools-go/cm"
)

func lift_GroupVersion(f0 *uint8, f1 uint32, f2 *uint8, f3 uint32) (v GroupVersion) {
	v.Group = cm.LiftString[string](f0, f1)
	v.Version = cm.LiftString[string](f2, f3)
	return
}

func lift_OptionGroupVersion(f0 uint32, f1 *uint8, f2 uint32, f3 *uint8, f4 uint32) (v cm.Option[GroupVersion]) {
	if f0 == 0 {
		return
	}
	return (cm.Option[GroupVersion])(cm.Some[GroupVersion](lift_GroupVersion((*uint8)(f1), (uint32)(f2), (*uint8)(f3), (uint32)(f4))))
}

func lift_ConversionRequest(f0 *uint8, f1 uint32, f2 *RawObject, f3 uint32, f4 uint32, f5 *uint8, f6 uint32, f7 *uint8, f8 uint32) (v ConversionRequest) {
	v.UID = cm.LiftString[string](f0, f1)
	v.Objects = cm.LiftList[cm.List[RawObject]](f2, f3)
	v.TargetVersion = lift_OptionGroupVersion(f4, f5, f6, f7, f8)
	return
}
