// Code generated by wit-bindgen-go. DO NOT EDIT.

package conversion

// This file contains wasmimport and wasmexport declarations for "grafana:plugin@0.0.1".

//go:wasmexport convert-objects
//export convert-objects
func wasmexport_ConvertObjects(req0 *uint8, req1 uint32, req2 *RawObject, req3 uint32, req4 uint32, req5 *uint8, req6 uint32, req7 *uint8, req8 uint32) (result *ConversionResponse) {
	req := lift_ConversionRequest((*uint8)(req0), (uint32)(req1), (*RawObject)(req2), (uint32)(req3), (uint32)(req4), (*uint8)(req5), (uint32)(req6), (*uint8)(req7), (uint32)(req8))
	result_ := Exports.ConvertObjects(req)
	result = &result_
	return
}
